[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "neuroflux"
version = "0.0.0"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
description = "A preprocessing pipeline for multimodal (PET and T1-weighted sMRI) scans."
keywords = ["deep learning", "medical imaging", "neuroimaging", "multimodal ai", "preprocessing"]
authors = [
    { name = "Antonio Scardace", email = "antonio.scardace@phd.unict.it" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "hd-bet==2.0.1",
    "indexed_gzip>=0.7.0",
    "intensity-normalization==2.2.4",
    "nibabel==3.2.2",
    "nnunetv2==2.6.2",
    "nvidia-ml-py==13.580.82",
    "psutil==7.0.0",
    "pydicom==2.4.4"
]

[tool.setuptools.packages.find]
where = ["."]