MRI_MAT_PREFIX="mri_to_mni_"
MRI_TO_MNI_MAT="${MRI_MAT_PREFIX}0GenericAffine.mat"
MRI_WARPED_TEMP="${MRI_MAT_PREFIX}Warped.nii.gz"
MRI_WARPED="warped.nii.gz"
MRI_CORRECTED="corrected.nii.gz"
MRI_SKULLSTRIP="skullstrip.nii.gz"
MRI_BRAIN_MASK_TEMP="skullstrip_bet.nii.gz"
MRI_BRAIN_MASK="brain_mask.nii.gz"
MRI_PREPROCESSED="preprocessed.nii.gz"
MRI_SEGM="segm.nii.gz"
MRI_SEGM_4D="segm_4d.nii.gz"
MRI_SEGM_CSV="volumes.csv"

PET_MAT_PREFIX="pet_to_mri_"
PET_TO_MRI_MAT="${PET_MAT_PREFIX}0GenericAffine.mat"
PET_STATIC="static.nii.gz"
PET_WARPED="warped.nii.gz"
PET_SKULLSTRIP="skullstrip.nii.gz"
PET_PVC="pvc.nii.gz"
PET_SUVR="suvr_norm.nii.gz"
PET_CSV="uptakes.csv"

UID_GID="$(id -u):$(id -g)"